#!/bin/sh

usage() {
  printf '%b' \
    'Remove files from cwd.\n\n' \
    \
    'Usage:\n' \
    '  clean [options] <dir>...\n\n' \
    \
    'Options:\n' \
    '  -x, --exec      remove executable files.\n' \
    '  -f, --force     do not prompt before removal.\n' \
    '  -h, --help      display this message and exit.\n'
}

x_flag=0 # executable.
f_flag=0 # force.

main() {
  get_opts "${@}"
  check_opts
  exec_opts
}

check_opts() {
  if [ ${x_flag} -eq 0 ]; then
    usage
    exit 0
  fi
}

get_opts() {
  while getopts ':xfh' opt; do
    case ${opt} in
    x) x_flag=1 ;;
    f) f_flag=1 ;;
    h)
      usage && exit 0
      ;;
    *) echo "${0}: unknown option: ${OPTARG}" >&2 && exit 1 ;;
    esac
  done
}

exec_opts() {
  if [ ${x_flag} -eq 1 ]; then
    [ ${f_flag} -eq 0 ] && rm_opts="-vi" || rm_opts='-v'
    find . -executable -type f -exec rm "${rm_opts}" {} \;
  fi
}

main "${@}"
